def read_file(folder: str, file: str) -> str: ...
def regular_labels(file_no_spaces: str) -> Iterator[Match]: ...
def start_labels(script_file_no_spaces: str) -> Iterator[Match]: ...
def parse_start(label: str) -> Tuple(str, [List[str]]): ...
def parse_regular(label: str) -> Tuple(str, [List[str]]): ...
def story_schema(folder: str) -> Dict[str, List[Tuple[str, List[str]]]]: ...
def print_schema(folder: str) -> None: ...
def viz_js(schema: Dict[str, List[Tuple[str, List[str]]]]) -> None: ...
